status = error
name = SparkLogConfig

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %-5p %c: %m%n

rootLogger.level = error
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

logger.spark.name = org.apache.spark
logger.spark.level = error

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error

logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = error